### ISSUE TITLE
Export a `pprintln` 

### ISSUE THREAD

**Issue by tlienart** [rbt-lang/PrettyPrinting.jl#1]
Hello,

I've recently started using your package and it's proving very useful when displaying the output of julia code cells on a website with JuDoc, however I noticed it doesn't skip a line after printing so this:

```julia
function foo()
  nt = (a=5,b=7,c=10)
  nt |> pprint
  nt |> pprint
end
```

gives

```
(a = 5, b = 7, c = 10)(a = 5, b = 7, c = 10)
```

(of course it's a silly example but basically the second time it's called, things appear on the same line).

So could their either be the introduction of a lineskip by default OR if that's not desirable, could there be a secondary function `pprintln` defined as:

```julia
pprintln(io, s) = (pprint(io, s); println(io))
pprintln(s) = pprintln(stdout,s)
```

thanks! (I'm happy to open a PR for this too)

**Comment by xitology** [comment]
Thanks for the suggestion. I was hesitating between making `pprint()` emit a trailing linebreak and adding `pprintln()`, but at the end decided to do the latter.
